[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer_runs = 200
via_ir = true
remappings = [
    '@oasisprotocol/sapphire-contracts/=node_modules/@oasisprotocol/sapphire-contracts/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    'forge-std/=node_modules/forge-std/src/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
